"""Load YAML configs from repo configs/ directory."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

import yaml

_SLUG_PATTERN = re.compile(r"^[a-z0-9]([a-z0-9_-]{0,62})$")


def repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def load_yaml(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as f:
        data = yaml.safe_load(f)
    if data is None:
        return {}
    if not isinstance(data, dict):
        raise ValueError(f"Expected mapping at {path}")
    return data


def normalize_provider_slug(slug: str) -> str:
    """Lowercase slug for `configs/vpns/<slug>.yaml`; raises ValueError if invalid."""
    s = slug.strip().lower()
    if not s or not _SLUG_PATTERN.match(s):
        raise ValueError(
            "Provider slug must be 1–63 chars: start with alphanumeric, then "
            "alphanumeric, hyphen, or underscore only. "
            f"Got {slug!r}."
        )
    return s


def _default_vpn_config_dict(slug: str) -> dict[str, Any]:
    parts = [p for p in re.split(r"[-_]+", slug) if p]
    title = " ".join(p.capitalize() for p in parts) if parts else slug
    return {
        "provider_name": title,
        "slug": slug,
        "connection_mode": "manual_gui",
        "locations": [],
        "credentials": {
            "username_env": None,
            "password_env": None,
        },
        "policy_urls": [],
    }


def _write_default_vpn_config(path: Path, slug: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# Auto-generated by vpn-leaks — edit provider_name, policy_urls, "
        "competitor_probe, locations, and credentials as needed.\n"
    )
    with path.open("w", encoding="utf-8") as f:
        f.write(header)
        yaml.dump(
            _default_vpn_config_dict(slug),
            f,
            default_flow_style=False,
            allow_unicode=True,
            sort_keys=False,
            width=1000,
        )


def load_vpn_config(slug: str, *, create_if_missing: bool = False) -> dict[str, Any]:
    """
    Load ``configs/vpns/<slug>.yaml``.

    When ``create_if_missing`` is True (e.g. ``vpn-leaks run`` / ``report``), a
    minimal YAML is written if the file does not exist. Slug is normalized to
    lowercase for the filename.
    """
    norm = normalize_provider_slug(slug)
    path = repo_root() / "configs" / "vpns" / f"{norm}.yaml"
    if path.is_file():
        return load_yaml(path)
    if create_if_missing:
        _write_default_vpn_config(path, norm)
        return load_yaml(path)
    raise FileNotFoundError(f"Missing VPN config: {path}")


def load_leak_tests_config() -> dict[str, Any]:
    path = repo_root() / "configs" / "tools" / "leak-tests.yaml"
    return load_yaml(path) if path.is_file() else {}


def load_attribution_config() -> dict[str, Any]:
    path = repo_root() / "configs" / "tools" / "attribution.yaml"
    return load_yaml(path) if path.is_file() else {}


def methodology_config_hints(vpn_cfg: dict[str, Any]) -> list[str]:
    """Non-fatal reminders for website-exposure methodology completeness."""
    msgs: list[str] = []
    cp = vpn_cfg.get("competitor_probe")
    doms: list[Any] = []
    if isinstance(cp, dict):
        doms = list(cp.get("provider_domains") or [])
    if not doms:
        msgs.append(
            "competitor_probe.provider_domains is empty — automated Phase 8–9 "
            "website-exposure methodology will be skipped.",
        )
    if not (vpn_cfg.get("surface_urls") or []):
        msgs.append(
            "surface_urls is empty — host inventory will rely on competitor_probe URLs only.",
        )
    urls = vpn_cfg.get("policy_urls") or []
    if not urls:
        msgs.append(
            "policy_urls is empty — no VPN marketing/policy pages will be fetched for this slug.",
        )
    return msgs
